services:
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - ./bright-lives-theme:/var/www/html/wp-content/themes/bright-lives-theme
      - ./plugins:/var/www/html/wp-content/plugins
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
volumes:
  mysql: {}
